export interface AbbreviationEntry {
  abbr: string;
  longForm: string;
  /** Chapter slugs where this abbreviation is introduced or central. */
  chapters: string[];
}

/**
 * Every abbreviation spelled out across the curriculum, alphabetized case-insensitively.
 * Kept as a flat list — the glossary page handles grouping/searching.
 */
export const ABBREVIATIONS: AbbreviationEntry[] = [
  { abbr: "3DGS", longForm: "3D Gaussian Splatting", chapters: ["3d-gaussian-splatting-fundamentals", "rasterization-and-optimization-in-3dgs", "capstone-3d-gaussian-splatting-renderer"] },
  { abbr: "A2C", longForm: "Advantage Actor-Critic", chapters: ["actor-critic-architectures"] },
  { abbr: "AdaBoost", longForm: "Adaptive Boosting", chapters: ["ensembles-boosting-and-adaboost", "capstone-tabular-kaggle-classifier"] },
  { abbr: "Adam", longForm: "Adaptive Moment Estimation", chapters: ["optimizers-momentum-rmsprop-adam"] },
  { abbr: "AdamW", longForm: "Adam with Decoupled Weight Decay", chapters: ["optimizers-momentum-rmsprop-adam", "weight-decay-vs-l2"] },
  { abbr: "ANN", longForm: "Approximate Nearest Neighbor", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "ARIMA", longForm: "AutoRegressive Integrated Moving Average", chapters: ["time-series-forecasting"] },
  { abbr: "AUC", longForm: "Area Under the Curve", chapters: ["roc-curve-and-auc"] },
  { abbr: "autograd", longForm: "Automatic Differentiation", chapters: ["capstone-autograd-engine", "backpropagation-step-by-step"] },
  { abbr: "AWQ", longForm: "Activation-aware Weight Quantization", chapters: ["model-quantization-awq-gptq-gguf", "capstone-design-a-monitored-serving-pipeline"] },
  { abbr: "BCE", longForm: "Binary Cross-Entropy", chapters: ["cross-entropy-loss"] },
  { abbr: "BERT", longForm: "Bidirectional Encoder Representations from Transformers", chapters: ["interleaved-multimodal-generation", "transfer-learning-and-fine-tuning"] },
  { abbr: "BF16", longForm: "Brain Floating Point 16-bit", chapters: ["mixed-precision-training"] },
  { abbr: "BitNet", longForm: "1.58-bit Ternary Neural Network", chapters: ["model-quantization-awq-gptq-gguf"] },
  { abbr: "BPE", longForm: "Byte-Pair Encoding", chapters: ["tokenization"] },
  { abbr: "CLIP", longForm: "Contrastive Language–Image Pretraining", chapters: ["contrastive-learning", "vision-language-models-assembled"] },
  { abbr: "CNN", longForm: "Convolutional Neural Network", chapters: ["a-minimal-cnn", "capstone-classify-digits"] },
  { abbr: "CoT", longForm: "Chain-of-Thought", chapters: ["reasoning-models-and-test-time-compute", "capstone-train-a-reasoning-model-grpo"] },
  { abbr: "DBSCAN", longForm: "Density-Based Spatial Clustering of Applications with Noise", chapters: ["alternative-clustering-dbscan", "capstone-customer-segmentation-engine"] },
  { abbr: "DDIM", longForm: "Denoising Diffusion Implicit Models", chapters: ["deterministic-sampling-ddim"] },
  { abbr: "DDP", longForm: "Distributed Data Parallel", chapters: ["distributed-training-parallelism"] },
  { abbr: "DDPM", longForm: "Denoising Diffusion Probabilistic Models", chapters: ["diffusion-models"] },
  { abbr: "DiT", longForm: "Diffusion Transformer", chapters: ["diffusion-transformers-dit", "capstone-build-a-flow-matching-sampler"] },
  { abbr: "DPO", longForm: "Direct Preference Optimization", chapters: ["direct-preference-optimization"] },
  { abbr: "DQN", longForm: "Deep Q-Network", chapters: ["deep-q-networks"] },
  { abbr: "ELBO", longForm: "Evidence Lower Bound", chapters: ["variational-autoencoders"] },
  { abbr: "F1", longForm: "F1 Score", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "FAISS", longForm: "Facebook AI Similarity Search", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "FGSM", longForm: "Fast Gradient Sign Method", chapters: ["adversarial-examples-and-robustness"] },
  { abbr: "FlashAttention", longForm: "Fast, Memory-Efficient Exact Attention with IO-Awareness", chapters: ["flash-attention-algorithms"] },
  { abbr: "FN", longForm: "False Negative", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "FP", longForm: "False Positive", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "FP16", longForm: "16-bit Floating Point", chapters: ["mixed-precision-training"] },
  { abbr: "FP32", longForm: "32-bit Single Precision Floating Point", chapters: ["mixed-precision-training"] },
  { abbr: "FPR", longForm: "False Positive Rate", chapters: ["roc-curve-and-auc"] },
  { abbr: "FSDP", longForm: "Fully Sharded Data Parallel", chapters: ["distributed-training-parallelism"] },
  { abbr: "GAN", longForm: "Generative Adversarial Network", chapters: ["vq-vae-discrete-latents"] },
  { abbr: "GBM", longForm: "Gradient Boosting Machine", chapters: ["gradient-boosting-machines"] },
  { abbr: "GeLU", longForm: "Gaussian Error Linear Unit", chapters: ["activation-functions"] },
  { abbr: "GGUF", longForm: "GPT-Generated Unified Format (quantization format)", chapters: ["model-quantization-awq-gptq-gguf"] },
  { abbr: "GloVe", longForm: "Global Vectors for Word Representation", chapters: ["word-embeddings"] },
  { abbr: "GPT", longForm: "Generative Pre-trained Transformer", chapters: ["tokenization", "the-modern-llm-post-training-pipeline"] },
  { abbr: "GPTQ", longForm: "Accurate Post-Training Quantization for Generative Pre-trained Transformers", chapters: ["model-quantization-awq-gptq-gguf"] },
  { abbr: "GRPO", longForm: "Group Relative Policy Optimization", chapters: ["group-relative-policy-optimization-grpo", "capstone-train-a-reasoning-model-grpo"] },
  { abbr: "GRU", longForm: "Gated Recurrent Unit", chapters: ["gru"] },
  { abbr: "HBM", longForm: "High Bandwidth Memory", chapters: ["flash-attention-algorithms", "gpu-memory-hierarchies-and-profiling"] },
  { abbr: "HDBSCAN", longForm: "Hierarchical Density-Based Spatial Clustering of Applications with Noise", chapters: ["alternative-clustering-dbscan", "capstone-customer-segmentation-engine"] },
  { abbr: "HNSW", longForm: "Hierarchical Navigable Small World", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "IoU", longForm: "Intersection over Union", chapters: ["object-detection-and-segmentation"] },
  { abbr: "IVF-PQ", longForm: "Inverted File with Product Quantization", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "JSON", longForm: "JavaScript Object Notation", chapters: ["function-calling-and-tool-use"] },
  { abbr: "k-NN", longForm: "k-Nearest Neighbors", chapters: ["k-nearest-neighbors"] },
  { abbr: "KL divergence", longForm: "Kullback–Leibler Divergence", chapters: ["kl-divergence-and-mutual-information", "variational-autoencoders"] },
  { abbr: "KTO", longForm: "Kahneman-Tversky Optimization", chapters: ["advanced-preference-kto-simpo"] },
  { abbr: "KV cache", longForm: "Key-Value Cache", chapters: ["inference-acceleration-pagedattention-vllm", "capstone-design-a-monitored-serving-pipeline"] },
  { abbr: "L1", longForm: "Lasso Regularization / Manhattan Norm", chapters: ["lasso-regression-l1"] },
  { abbr: "L2", longForm: "Ridge Regularization / Euclidean Norm", chapters: ["ridge-regression-l2"] },
  { abbr: "LDA", longForm: "Linear Discriminant Analysis", chapters: ["linear-discriminant-analysis"] },
  { abbr: "LightGBM", longForm: "Light Gradient Boosting Machine", chapters: ["modern-boosters-xgboost-and-lightgbm"] },
  { abbr: "LOF", longForm: "Local Outlier Factor", chapters: ["anomaly-detection"] },
  { abbr: "LoRA", longForm: "Low-Rank Adaptation", chapters: ["transfer-learning-and-fine-tuning", "the-modern-llm-post-training-pipeline"] },
  { abbr: "LSTM", longForm: "Long Short-Term Memory", chapters: ["vanishing-gradients-and-lstms"] },
  { abbr: "MAE", longForm: "Mean Absolute Error", chapters: ["loss-functions-mse-vs-mae"] },
  { abbr: "Mamba", longForm: "Selective State-Space Architecture", chapters: ["selective-state-spaces", "capstone-transformer-vs-mamba"] },
  { abbr: "MAP", longForm: "Maximum A Posteriori", chapters: ["maximum-a-posteriori-estimation", "capstone-bayesian-classifier"] },
  { abbr: "MCTS", longForm: "Monte Carlo Tree Search", chapters: ["process-reward-models-and-tree-search"] },
  { abbr: "MDP", longForm: "Markov Decision Process", chapters: ["markov-decision-processes"] },
  { abbr: "MEMIT", longForm: "Mass-Editing Memory in a Transformer", chapters: ["model-editing-rome-memit"] },
  { abbr: "MLE", longForm: "Maximum Likelihood Estimation", chapters: ["maximum-likelihood-estimation", "capstone-bayesian-classifier"] },
  { abbr: "MLP", longForm: "Multi-Layer Perceptron", chapters: ["multi-layer-perceptrons", "the-forward-pass"] },
  { abbr: "MoE", longForm: "Mixture of Experts", chapters: ["distributed-training-parallelism"] },
  { abbr: "MSE", longForm: "Mean Squared Error", chapters: ["loss-functions-mse-vs-mae"] },
  { abbr: "NeRF", longForm: "Neural Radiance Field", chapters: ["neural-radiance-fields-nerf", "instant-ngp-and-hash-encoding"] },
  { abbr: "NMS", longForm: "Non-Maximum Suppression", chapters: ["object-detection-and-segmentation"] },
  { abbr: "ODE", longForm: "Ordinary Differential Equation", chapters: ["flow-matching", "deterministic-sampling-ddim"] },
  { abbr: "OLS", longForm: "Ordinary Least Squares", chapters: ["linear-regression-fitting-a-line"] },
  { abbr: "PagedAttention", longForm: "Paged Attention Memory Management (vLLM)", chapters: ["inference-acceleration-pagedattention-vllm"] },
  { abbr: "PCA", longForm: "Principal Component Analysis", chapters: ["pca-directions-of-maximum-variance", "capstone-svd-image-compressor"] },
  { abbr: "PGD", longForm: "Projected Gradient Descent", chapters: ["adversarial-examples-and-robustness"] },
  { abbr: "PPO", longForm: "Proximal Policy Optimization", chapters: ["proximal-policy-optimization-ppo", "reinforcement-learning-from-human-feedback"] },
  { abbr: "PR curve", longForm: "Precision-Recall Curve", chapters: ["roc-curve-and-auc"] },
  { abbr: "PRM", longForm: "Process Reward Model", chapters: ["process-reward-models-and-tree-search"] },
  { abbr: "PSI", longForm: "Population Stability Index", chapters: ["model-monitoring-and-drift"] },
  { abbr: "RAG", longForm: "Retrieval-Augmented Generation", chapters: ["retrieval-augmented-generation", "capstone-image-text-search-engine"] },
  { abbr: "RBF", longForm: "Radial Basis Function", chapters: ["the-kernel-trick"] },
  { abbr: "ReAct", longForm: "Reasoning and Acting", chapters: ["react-reasoning-and-acting"] },
  { abbr: "Reflexion", longForm: "Self-Reflection in Agents", chapters: ["environment-feedback-and-reflexion"] },
  { abbr: "ReLU", longForm: "Rectified Linear Unit", chapters: ["activation-functions"] },
  { abbr: "ResNet", longForm: "Residual Neural Network", chapters: ["resnet-and-residual-connections"] },
  { abbr: "RLAIF", longForm: "Reinforcement Learning from AI Feedback", chapters: ["constitutional-ai-and-rlaif"] },
  { abbr: "RLHF", longForm: "Reinforcement Learning from Human Feedback", chapters: ["reinforcement-learning-from-human-feedback"] },
  { abbr: "RLVR", longForm: "Reinforcement Learning with Verifiable Rewards", chapters: ["reinforcement-learning-with-verifiable-rewards-rlvr", "capstone-train-a-reasoning-model-grpo"] },
  { abbr: "RMSNorm", longForm: "Root Mean Square Normalization", chapters: ["rmsnorm"] },
  { abbr: "RMSProp", longForm: "Root Mean Square Propagation", chapters: ["optimizers-momentum-rmsprop-adam"] },
  { abbr: "RNN", longForm: "Recurrent Neural Network", chapters: ["recurrent-neural-networks"] },
  { abbr: "ROC", longForm: "Receiver Operating Characteristic", chapters: ["roc-curve-and-auc"] },
  { abbr: "ROME", longForm: "Rank-One Model Editing", chapters: ["model-editing-rome-memit"] },
  { abbr: "RoPE", longForm: "Rotary Position Embedding", chapters: ["rotary-position-embedding-rope", "context-window-scaling-yarn"] },
  { abbr: "SAE", longForm: "Sparse Autoencoder", chapters: ["mechanistic-interpretability-and-saes", "capstone-red-team-and-patch-a-model"] },
  { abbr: "ScaNN", longForm: "Scalable Nearest Neighbors", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "SDF", longForm: "Signed Distance Function", chapters: ["representing-3d-data"] },
  { abbr: "SFT", longForm: "Supervised Fine-Tuning", chapters: ["instruction-tuning-and-sft", "the-modern-llm-post-training-pipeline"] },
  { abbr: "SGD", longForm: "Stochastic Gradient Descent", chapters: ["gradient-descent-variants"] },
  { abbr: "SimPO", longForm: "Simple Preference Optimization", chapters: ["advanced-preference-kto-simpo"] },
  { abbr: "SRAM", longForm: "Static Random-Access Memory", chapters: ["flash-attention-algorithms", "gpu-memory-hierarchies-and-profiling"] },
  { abbr: "SSM", longForm: "State-Space Model", chapters: ["state-space-models", "selective-state-spaces"] },
  { abbr: "SVD", longForm: "Singular Value Decomposition", chapters: ["svd-and-eigendecomposition", "capstone-svd-image-compressor"] },
  { abbr: "SVM", longForm: "Support Vector Machine", chapters: ["support-vector-machines", "the-kernel-trick"] },
  { abbr: "SWE-bench", longForm: "Software Engineering Benchmark", chapters: ["agent-benchmarking-and-swe-bench"] },
  { abbr: "t-SNE", longForm: "t-Distributed Stochastic Neighbor Embedding", chapters: ["non-linear-dimensionality-reduction-tsne"] },
  { abbr: "TN", longForm: "True Negative", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "TP", longForm: "True Positive", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "TPR", longForm: "True Positive Rate", chapters: ["roc-curve-and-auc"] },
  { abbr: "U-Net", longForm: "U-Shaped Convolutional Network", chapters: ["semantic-segmentation-and-unet"] },
  { abbr: "UCB", longForm: "Upper Confidence Bound", chapters: ["multi-armed-bandits"] },
  { abbr: "UMAP", longForm: "Uniform Manifold Approximation and Projection", chapters: ["umap-manifold-approximation", "capstone-customer-segmentation-engine"] },
  { abbr: "VAE", longForm: "Variational Autoencoder", chapters: ["variational-autoencoders"] },
  { abbr: "ViT", longForm: "Vision Transformer", chapters: ["transfer-learning-and-fine-tuning"] },
  { abbr: "VLA", longForm: "Vision-Language-Action (Robotics)", chapters: ["embodied-ai-and-vla-robotics", "capstone-design-a-monitored-serving-pipeline"] },
  { abbr: "vLLM", longForm: "Virtual Large Language Model (Serving Engine)", chapters: ["inference-acceleration-pagedattention-vllm", "capstone-design-a-monitored-serving-pipeline"] },
  { abbr: "VLM", longForm: "Vision-Language Model", chapters: ["vision-language-models-assembled", "capstone-image-text-search-engine"] },
  { abbr: "VQ-VAE", longForm: "Vector-Quantized Variational Autoencoder", chapters: ["vq-vae-discrete-latents"] },
  { abbr: "XGBoost", longForm: "eXtreme Gradient Boosting", chapters: ["modern-boosters-xgboost-and-lightgbm"] },
  { abbr: "XOR", longForm: "Exclusive OR", chapters: ["the-perceptron"] },
  { abbr: "YaRN", longForm: "Yet another RoPE extensioN method", chapters: ["context-window-scaling-yarn"] },
  { abbr: "YOLO", longForm: "You Only Look Once", chapters: ["one-stage-vs-two-stage-detectors"] },
  { abbr: "ZeRO", longForm: "Zero Redundancy Optimizer", chapters: ["distributed-training-parallelism"] },
];
