export interface AbbreviationEntry {
  abbr: string;
  longForm: string;
  /** Chapter slugs where this abbreviation is introduced or central. */
  chapters: string[];
}

/**
 * Every abbreviation spelled out somewhere in the curriculum, alphabetized case-insensitively.
 * Kept as a flat list — the glossary page handles grouping/searching.
 */
export const ABBREVIATIONS: AbbreviationEntry[] = [
  { abbr: "AdaBoost", longForm: "Adaptive Boosting", chapters: ["ensembles-boosting", "capstone-classifier-pipeline"] },
  { abbr: "Adam", longForm: "Adaptive Moment Estimation", chapters: ["optimizers-momentum-rmsprop-adam"] },
  { abbr: "ARIMA", longForm: "AutoRegressive Integrated Moving Average", chapters: ["time-series-forecasting"] },
  { abbr: "AUC", longForm: "Area Under the Curve", chapters: ["roc-curve-and-auc"] },
  { abbr: "autograd", longForm: "automatic differentiation", chapters: ["backpropagation-step-by-step"] },
  { abbr: "BERT", longForm: "Bidirectional Encoder Representations from Transformers", chapters: ["bert-and-masked-language-modeling"] },
  { abbr: "BPE", longForm: "Byte-Pair Encoding", chapters: ["tokenization"] },
  { abbr: "CLIP", longForm: "Contrastive Language–Image Pretraining", chapters: ["contrastive-learning"] },
  { abbr: "CNN", longForm: "Convolutional Neural Network", chapters: ["a-minimal-cnn", "saliency-maps"] },
  { abbr: "DBSCAN", longForm: "Density-Based Spatial Clustering of Applications with Noise", chapters: ["alternative-clustering-dbscan"] },
  { abbr: "DPO", longForm: "Direct Preference Optimization", chapters: ["direct-preference-optimization"] },
  { abbr: "ELU", longForm: "Exponential Linear Unit", chapters: ["linear-attention"] },
  { abbr: "F1", longForm: "F1 score", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "FAISS", longForm: "Facebook AI Similarity Search", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "FGSM", longForm: "Fast Gradient Sign Method", chapters: ["adversarial-examples-and-robustness"] },
  { abbr: "FIFO", longForm: "First In, First Out", chapters: ["agent-memory"] },
  { abbr: "FN", longForm: "False Negative", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "FP", longForm: "False Positive", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "FPR", longForm: "False Positive Rate", chapters: ["roc-curve-and-auc"] },
  { abbr: "GAN", longForm: "Generative Adversarial Network", chapters: ["generative-adversarial-networks"] },
  { abbr: "GAT", longForm: "Graph Attention Network", chapters: ["graph-attention-networks"] },
  { abbr: "GCN", longForm: "Graph Convolutional Network", chapters: ["message-passing-and-gcn"] },
  { abbr: "GloVe", longForm: "Global Vectors", chapters: ["word-embeddings"] },
  { abbr: "GNN", longForm: "Graph Neural Network", chapters: ["graphs-as-data"] },
  { abbr: "GPT", longForm: "Generative Pre-trained Transformer", chapters: ["tokenization", "bert-and-masked-language-modeling"] },
  { abbr: "Grad-CAM", longForm: "Gradient-weighted Class Activation Mapping", chapters: ["grad-cam"] },
  { abbr: "GRU", longForm: "Gated Recurrent Unit", chapters: ["gru"] },
  { abbr: "HNSW", longForm: "Hierarchical Navigable Small World", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "IoU", longForm: "Intersection over Union", chapters: ["object-detection-and-segmentation"] },
  { abbr: "IVF", longForm: "Inverted File index", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "JSON", longForm: "JavaScript Object Notation", chapters: ["function-calling-and-tool-use"] },
  { abbr: "KL divergence", longForm: "Kullback–Leibler divergence", chapters: ["kl-divergence-and-mutual-information"] },
  { abbr: "kNN", longForm: "k-Nearest Neighbors", chapters: ["k-nearest-neighbors"] },
  { abbr: "KV cache", longForm: "Key-Value cache", chapters: ["inference-optimization-and-deployment"] },
  { abbr: "L1", longForm: "Lasso (regularization)", chapters: ["regularization-l1-vs-l2"] },
  { abbr: "L2", longForm: "Ridge (regularization)", chapters: ["regularization-l1-vs-l2"] },
  { abbr: "LIME", longForm: "Local Interpretable Model-agnostic Explanations", chapters: ["lime"] },
  { abbr: "LoRA", longForm: "Low-Rank Adaptation", chapters: ["lora-and-parameter-efficient-fine-tuning"] },
  { abbr: "LSTM", longForm: "Long Short-Term Memory", chapters: ["vanishing-gradients-and-lstms"] },
  { abbr: "MAE", longForm: "Mean Absolute Error", chapters: ["loss-functions-mse-vs-mae"] },
  { abbr: "MDP", longForm: "Markov Decision Process", chapters: ["markov-decision-processes"] },
  { abbr: "MoE", longForm: "Mixture of Experts", chapters: ["mixture-of-experts"] },
  { abbr: "MSE", longForm: "Mean Squared Error", chapters: ["loss-functions-mse-vs-mae"] },
  { abbr: "PCA", longForm: "Principal Component Analysis", chapters: ["pca-directions-of-maximum-variance"] },
  { abbr: "PDP", longForm: "Partial Dependence Plot", chapters: ["partial-dependence-plots"] },
  { abbr: "RBF", longForm: "Radial Basis Function", chapters: ["the-kernel-trick"] },
  { abbr: "ReAct", longForm: "Reasoning and Acting", chapters: ["react-reasoning-and-acting"] },
  { abbr: "ReLU", longForm: "Rectified Linear Unit", chapters: ["activation-functions"] },
  { abbr: "RLAIF", longForm: "Reinforcement Learning from AI Feedback", chapters: ["constitutional-ai-and-rlaif"] },
  { abbr: "RLHF", longForm: "Reinforcement Learning from Human Feedback", chapters: ["reinforcement-learning-from-human-feedback"] },
  { abbr: "RMSProp", longForm: "Root Mean Square Propagation", chapters: ["optimizers-momentum-rmsprop-adam"] },
  { abbr: "RNN", longForm: "Recurrent Neural Network", chapters: ["recurrent-neural-networks"] },
  { abbr: "ROC", longForm: "Receiver Operating Characteristic", chapters: ["roc-curve-and-auc"] },
  { abbr: "SAE", longForm: "Sparse Autoencoder", chapters: ["mechanistic-interpretability-and-saes"] },
  { abbr: "ScaNN", longForm: "Scalable Nearest Neighbors", chapters: ["vector-databases-and-ann-search"] },
  { abbr: "SHAP", longForm: "SHapley Additive exPlanations", chapters: ["shap-for-real-models"] },
  { abbr: "SSE", longForm: "Sum of Squared Errors", chapters: ["linear-regression-fitting-a-line"] },
  { abbr: "SVD", longForm: "Singular Value Decomposition", chapters: ["svd-and-eigendecomposition"] },
  { abbr: "SVM", longForm: "Support Vector Machine", chapters: ["support-vector-machines"] },
  { abbr: "TN", longForm: "True Negative", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "TP", longForm: "True Positive", chapters: ["confusion-matrix-precision-recall-f1"] },
  { abbr: "TPR", longForm: "True Positive Rate", chapters: ["roc-curve-and-auc"] },
  { abbr: "USD", longForm: "US Dollars", chapters: ["capstone-build-a-tool-using-agent"] },
  { abbr: "VAE", longForm: "Variational Autoencoder", chapters: ["variational-autoencoders"] },
  { abbr: "ViT", longForm: "Vision Transformer", chapters: ["vision-transformers"] },
  { abbr: "VQ-VAE", longForm: "Vector-Quantized Variational Autoencoder", chapters: ["vq-vae-discrete-latents"] },
  { abbr: "XOR", longForm: "Exclusive OR", chapters: ["capstone-train-a-tiny-network"] },
];
