export interface ChapterMeta {
  slug: string;
  part: string;
  chapterNumber: number;
  title: string;
  blurb: string;
  capstone?: boolean;
}

/**
 * The full 23-Part, 229-Chapter Zero-to-Hero AI & Machine Learning Curriculum.
 * Single source of truth for the home page, search, chapter headers, and navigation.
 */
export const CURRICULUM: ChapterMeta[] = [
  // =========================================================================
  // PHASE 1: MATHEMATICAL & STATISTICAL FOUNDATIONS
  // =========================================================================

  // ---------- Part I — Calculus, Optimization & Gradients ----------
  {
    slug: "what-is-a-derivative",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 1,
    title: "What is a derivative?",
    blurb: "Drag a point along a curve, watch the tangent line, and find the exact spot where the slope hits zero.",
  },
  {
    slug: "the-gradient-in-multiple-dimensions",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 2,
    title: "The gradient in multiple dimensions",
    blurb: "Extend downhill descent to multiple parameters simultaneously on a 3D loss surface.",
  },
  {
    slug: "the-chain-rule",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 3,
    title: "The chain rule",
    blurb: "Drag a point through linked functions and watch slopes multiply through a computational graph.",
  },
  {
    slug: "jacobians-and-hessians",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 4,
    title: "Jacobians & Hessians",
    blurb: "Matrix derivatives, vector-valued transformations, and second-order curvature.",
  },
  {
    slug: "taylor-series-approximations",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 5,
    title: "Taylor series approximations",
    blurb: "Approximate complex loss landscapes with linear tangents and quadratic bowls.",
  },
  {
    slug: "convexity-and-optimization-landscapes",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 6,
    title: "Convexity & optimization landscapes",
    blurb: "Split a single convex bowl into non-convex wells and saddle points.",
  },
  {
    slug: "gradient-descent",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 7,
    title: "Gradient descent",
    blurb: "Take steps against the gradient, tune learning rates, and watch overshooting vs. divergence.",
  },
  {
    slug: "momentum-and-nesterov",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 8,
    title: "Momentum & Nesterov acceleration",
    blurb: "Give gradient descent inertia to damp oscillations in narrow ravines.",
  },
  {
    slug: "constrained-optimization-and-lagrange",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 9,
    title: "Constrained optimization & Lagrange multipliers",
    blurb: "Optimize objective functions subject to equality and inequality boundary constraints.",
  },
  {
    slug: "capstone-autograd-engine",
    part: "Part I — Calculus, Optimization & Gradients",
    chapterNumber: 10,
    title: "Build a computational graph & autograd engine",
    blurb: "Construct a scalar automatic differentiation engine from scratch.",
    capstone: true,
  },

  // ---------- Part II — Linear Algebra & Matrix Decompositions ----------
  {
    slug: "vectors-norms-and-inner-products",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 1,
    title: "Vectors, norms & inner products",
    blurb: "L1, L2, Linf norms, dot products, and cosine distance in feature space.",
  },
  {
    slug: "matrices-as-linear-transformations",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 2,
    title: "Matrices as linear transformations",
    blurb: "Watch a matrix rotate, stretch, shear, and project data vectors.",
  },
  {
    slug: "matrix-multiplication-as-projection",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 3,
    title: "Matrix multiplication as projection & subspace mapping",
    blurb: "Geometric perspectives on Ax=b and projecting onto column spaces.",
  },
  {
    slug: "determinants-and-matrix-inversion",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 4,
    title: "Determinants & matrix inversion",
    blurb: "Signed volume scaling, singularities, and when a linear system cannot be inverted.",
  },
  {
    slug: "eigenvalues-and-eigenvectors",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 5,
    title: "Eigenvalues & eigenvectors",
    blurb: "Find invariant axes where a matrix acts as a pure scalar stretch.",
  },
  {
    slug: "positive-semi-definite-matrices-and-covariance",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 6,
    title: "Positive semi-definite matrices & covariance",
    blurb: "Map the shape and spread of high-dimensional data clouds.",
  },
  {
    slug: "svd-and-eigendecomposition",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 7,
    title: "Singular Value Decomposition (SVD)",
    blurb: "Decompose any matrix into rotate-stretch-rotate factors.",
  },
  {
    slug: "low-rank-matrix-approximations",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 8,
    title: "Low-rank matrix approximations",
    blurb: "Compress information by truncating small singular values with the Eckart-Young theorem.",
  },
  {
    slug: "pca-directions-of-maximum-variance",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 9,
    title: "PCA: directions of maximum variance",
    blurb: "Derive principal component analysis by maximizing variance on orthogonal axes.",
  },
  {
    slug: "capstone-svd-image-compressor",
    part: "Part II — Linear Algebra & Matrix Decompositions",
    chapterNumber: 10,
    title: "Image compression & latent extraction via SVD/PCA",
    blurb: "Compress high-resolution imagery and extract eigenfaces interactively.",
    capstone: true,
  },

  // ---------- Part III — Probability, Information Theory & Bayesian Inference ----------
  {
    slug: "probability-outcomes-and-distributions",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 1,
    title: "Probability: outcomes & distributions",
    blurb: "Build discrete and continuous distributions that strictly sum to one.",
  },
  {
    slug: "expectation-variance-and-covariance",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 2,
    title: "Expectation, variance & covariance",
    blurb: "Compute first and second moments and measure joint linear variability.",
  },
  {
    slug: "joint-marginal-and-conditional-probability",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 3,
    title: "Joint, marginal & conditional probability",
    blurb: "Slice joint probability tables and integrate out nuisance variables.",
  },
  {
    slug: "conditional-probability-and-bayes-rule",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 4,
    title: "Conditional probability & Bayes' rule",
    blurb: "Update prior beliefs into posterior distributions as new evidence arrives.",
  },
  {
    slug: "common-probability-distributions",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 5,
    title: "Gaussian, Bernoulli, Poisson & Dirichlet distributions",
    blurb: "Explore the core distributions that govern machine learning models.",
  },
  {
    slug: "maximum-likelihood-estimation",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 6,
    title: "Maximum Likelihood Estimation (MLE)",
    blurb: "Find the parameter values that maximize the likelihood of observed data.",
  },
  {
    slug: "maximum-a-posteriori-estimation",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 7,
    title: "Maximum A Posteriori (MAP) estimation",
    blurb: "Inject prior knowledge into likelihood estimation to prevent overfitting.",
  },
  {
    slug: "information-and-entropy",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 8,
    title: "Information & entropy",
    blurb: "Quantify surprise in bits using Shannon entropy.",
  },
  {
    slug: "kl-divergence-and-mutual-information",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 9,
    title: "KL divergence & mutual information",
    blurb: "Measure relative entropy between true and approximate probability distributions.",
  },
  {
    slug: "capstone-bayesian-classifier",
    part: "Part III — Probability, Information Theory & Bayesian Inference",
    chapterNumber: 10,
    title: "Build a Bayesian spam classifier & anomaly detector",
    blurb: "Implement full MLE and MAP estimation pipelines with Bayesian updates.",
    capstone: true,
  },

  // =========================================================================
  // PHASE 2: CLASSICAL MACHINE LEARNING
  // =========================================================================

  // ---------- Part IV — Supervised Learning: Regression & Linear Classifiers ----------
  {
    slug: "linear-regression-fitting-a-line",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 1,
    title: "Linear regression & ordinary least squares",
    blurb: "Fit a line by solving the normal equations and inspect residual sum of squares.",
  },
  {
    slug: "loss-functions-mse-vs-mae",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 2,
    title: "Loss functions: MSE vs. MAE vs. Huber",
    blurb: "Analyze outlier sensitivity across squared, absolute, and robust losses.",
  },
  {
    slug: "ridge-regression-l2",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 3,
    title: "Ridge regression (L2 regularization)",
    blurb: "Penalize weight magnitudes to stabilize collinear predictors.",
  },
  {
    slug: "lasso-regression-l1",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 4,
    title: "Lasso regression (L1 regularization)",
    blurb: "Drive sparse feature selection through diamond-shaped geometric constraints.",
  },
  {
    slug: "elastic-net-regularization",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 5,
    title: "ElasticNet regularization",
    blurb: "Combine L1 sparsity with L2 grouping effect.",
  },
  {
    slug: "logistic-regression-and-the-sigmoid",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 6,
    title: "Logistic regression & the sigmoid",
    blurb: "Squash continuous linear outputs into class probabilities.",
  },
  {
    slug: "cross-entropy-loss",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 7,
    title: "Binary cross-entropy loss",
    blurb: "Derive log-loss for classification and analyze gradients near saturation.",
  },
  {
    slug: "multinomial-logistic-regression-and-softmax",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 8,
    title: "Multinomial logistic regression & softmax",
    blurb: "Generalize binary classification to K classes with normalized exponentials.",
  },
  {
    slug: "linear-discriminant-analysis",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 9,
    title: "Linear Discriminant Analysis (LDA)",
    blurb: "Maximize between-class separation while minimizing within-class variance.",
  },
  {
    slug: "naive-bayes-classifier",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 10,
    title: "The naive Bayes classifier",
    blurb: "Turn Part I's Bayes' rule into a full classifier, one independent feature at a time.",
  },
  {
    slug: "capstone-financial-risk-scorer",
    part: "Part IV — Supervised Learning: Regression & Linear Classifiers",
    chapterNumber: 11,
    title: "Build a calibrated financial risk scoring engine",
    blurb: "Construct and regularize a multi-class probabilistic linear classifier.",
    capstone: true,
  },

  // ---------- Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods ----------
  {
    slug: "decision-trees-information-gain",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 1,
    title: "Decision trees & information gain",
    blurb: "Recursively partition feature space using Shannon entropy and Gini impurity.",
  },
  {
    slug: "overfitting-and-pruning-a-tree",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 2,
    title: "Overfitting & cost-complexity pruning",
    blurb: "Prune overgrown decision trees to restore validation generalization.",
  },
  {
    slug: "ensembles-bagging-and-random-forests",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 3,
    title: "Ensembles I: Bagging & Random Forests",
    blurb: "Reduce variance by aggregating decorrelated bootstrap trees.",
  },
  {
    slug: "ensembles-boosting-and-adaboost",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 4,
    title: "Ensembles II: Boosting & AdaBoost",
    blurb: "Sequentially re-weight misclassified instances with weak learners.",
  },
  {
    slug: "gradient-boosting-machines",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 5,
    title: "Gradient Boosting Machines (GBM)",
    blurb: "Fit consecutive regression trees to the pseudo-residuals of any differentiable loss.",
  },
  {
    slug: "modern-boosters-xgboost-and-lightgbm",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 6,
    title: "Modern boosters: XGBoost & LightGBM",
    blurb: "Second-order Taylor expansions, histogram binning, and tree regularizers.",
  },
  {
    slug: "support-vector-machines",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 7,
    title: "Support Vector Machines (SVM)",
    blurb: "Construct maximum-margin separating hyperplanes using support vectors.",
  },
  {
    slug: "the-kernel-trick",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 8,
    title: "The kernel trick (RBF & Polynomial)",
    blurb: "Map non-linearly separable data into infinite-dimensional Hilbert spaces.",
  },
  {
    slug: "k-nearest-neighbors",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 9,
    title: "k-Nearest Neighbors (k-NN)",
    blurb: "Non-parametric instance-based voting across spatial distance metrics.",
  },
  {
    slug: "capstone-tabular-kaggle-classifier",
    part: "Part V — Non-Linear Models, Trees, Ensembles & Kernel Methods",
    chapterNumber: 10,
    title: "Build a high-performance tabular ML pipeline",
    blurb: "Benchmark Random Forest, XGBoost, and Kernel SVMs on complex datasets.",
    capstone: true,
  },

  // ---------- Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series ----------
  {
    slug: "k-means-clustering",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 1,
    title: "k-means clustering & Lloyd's algorithm",
    blurb: "Iteratively update cluster centroids and Voronoi partition cells.",
  },
  {
    slug: "kmeans-plus-plus-and-elbow-method",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 2,
    title: "k-means++ & the elbow method",
    blurb: "Probabilistic centroid seeding and inertia curve inflection analysis.",
  },
  {
    slug: "hierarchical-and-agglomerative-clustering",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 3,
    title: "Hierarchical & agglomerative clustering",
    blurb: "Dendrogram hierarchies with single, complete, and Ward's minimum variance linkage.",
  },
  {
    slug: "alternative-clustering-dbscan",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 4,
    title: "Density-based clustering: DBSCAN & HDBSCAN",
    blurb: "Discover arbitrary non-spherical cluster geometries and isolate noise points.",
  },
  {
    slug: "non-linear-dimensionality-reduction-tsne",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 5,
    title: "Non-linear dimensionality reduction: t-SNE",
    blurb: "Preserve local neighborhood probabilities using Student-t kernel matching.",
  },
  {
    slug: "umap-manifold-approximation",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 6,
    title: "UMAP (Uniform Manifold Approximation & Projection)",
    blurb: "Fuzzy simplicial sets and preserving global topological structure.",
  },
  {
    slug: "anomaly-detection",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 7,
    title: "Anomaly detection: Isolation Forests & LOF",
    blurb: "Isolate outliers via random recursive partitioning and local density ratios.",
  },
  {
    slug: "collaborative-filtering-and-matrix-factorization",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 8,
    title: "Recommender systems & matrix factorization",
    blurb: "Factorize sparse user-item interaction matrices with alternating least squares.",
  },
  {
    slug: "time-series-forecasting",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 9,
    title: "Time series forecasting: ARIMA & exponential smoothing",
    blurb: "Decompose trend, seasonality, and autoregressive lags for future projection.",
  },
  {
    slug: "capstone-customer-segmentation-engine",
    part: "Part VI — Unsupervised Learning, Clustering, Dimensionality & Time Series",
    chapterNumber: 10,
    title: "Build a customer segmentation & recommendation engine",
    blurb: "Unify UMAP, HDBSCAN, and collaborative filtering into a complete pipeline.",
    capstone: true,
  },

  // ---------- Part VII — Model Evaluation, Validation & Feature Engineering ----------
  {
    slug: "confusion-matrix-precision-recall-f1",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 1,
    title: "Confusion matrix, precision, recall & F1",
    blurb: "Diagnose classifier performance on severely imbalanced datasets.",
  },
  {
    slug: "roc-curve-and-auc",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 2,
    title: "ROC curves, AUC & PR curves",
    blurb: "Sweep decision thresholds and trace out discrimination ability.",
  },
  {
    slug: "cross-validation",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 3,
    title: "k-fold & stratified cross-validation",
    blurb: "Mitigate validation variance and prevent subtle data leakage.",
  },
  {
    slug: "bias-variance-tradeoff",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 4,
    title: "Bias-variance decomposition",
    blurb: "Decompose expected test error into irreducible noise, bias, and variance.",
  },
  {
    slug: "feature-engineering-and-scaling",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 5,
    title: "Feature scaling & transformation",
    blurb: "Standardize, normalize, and apply Power/Box-Cox transformations.",
  },
  {
    slug: "encoding-categorical-variables",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 6,
    title: "Encoding categorical variables",
    blurb: "One-hot, ordinal, target encoding, and weight-of-evidence techniques.",
  },
  {
    slug: "feature-selection-techniques",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 7,
    title: "Feature selection & dimensionality filtering",
    blurb: "Variance thresholds, mutual information scores, and recursive feature elimination.",
  },
  {
    slug: "hyperparameter-tuning",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 8,
    title: "Hyperparameter tuning: Grid, Random & Bayesian search",
    blurb: "Automate parameter sweeps using Optuna and Hyperband search strategies.",
  },
  {
    slug: "calibration-of-probabilities",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 9,
    title: "Probability calibration: Platt scaling & Isotonic regression",
    blurb: "Calibrate uncalibrated confidence outputs into true posterior probabilities.",
  },
  {
    slug: "capstone-evaluate-a-real-pipeline",
    part: "Part VII — Model Evaluation, Validation & Feature Engineering",
    chapterNumber: 10,
    title: "Grade and audit a machine learning pipeline honestly",
    blurb: "Execute complete cross-validation, hyperparameter tuning, and probability calibration.",
    capstone: true,
  },

  // =========================================================================
  // PHASE 3: DEEP LEARNING FOUNDATIONS & ARCHITECTURES
  // =========================================================================

  // ---------- Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers ----------
  {
    slug: "the-perceptron",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 1,
    title: "The perceptron & the XOR problem",
    blurb: "A single artificial neuron and why non-linear separation requires depth.",
  },
  {
    slug: "multi-layer-perceptrons",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 2,
    title: "Multi-Layer Perceptrons (MLP)",
    blurb: "Stack hidden layers to approximate arbitrary continuous functions.",
  },
  {
    slug: "activation-functions",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 3,
    title: "Activation functions: Sigmoid, Tanh, ReLU, GeLU & Swish",
    blurb: "Compare non-linearities and their derivative saturation profiles.",
  },
  {
    slug: "the-forward-pass",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 4,
    title: "The forward pass",
    blurb: "Trace matrix multiplications, biases, and activations layer by layer.",
  },
  {
    slug: "a-network-is-a-chain",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 5,
    title: "A network is a chain",
    blurb: "See why backpropagation is the chain rule applied backward through layers.",
  },
  {
    slug: "backpropagation-step-by-step",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 6,
    title: "Backpropagation, step by step",
    blurb: "Walk through analytical gradient computations by hand and verify against autograd.",
  },
  {
    slug: "loss-landscapes-in-high-dimensions",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 7,
    title: "Loss landscapes in high dimensions",
    blurb: "Explore saddle points, plateaus, ravines, and local minima.",
  },
  {
    slug: "gradient-descent-variants",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 8,
    title: "Stochastic & mini-batch gradient descent",
    blurb: "Batch size tradeoffs, noisy gradient estimates, and generalization.",
  },
  {
    slug: "optimizers-momentum-rmsprop-adam",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 9,
    title: "Optimizers: Momentum, RMSProp, Adam & AdamW",
    blurb: "Race adaptive optimizers down complex loss surfaces.",
  },
  {
    slug: "capstone-mini-pytorch-framework",
    part: "Part VIII — Neural Network Fundamentals, Backpropagation & Optimizers",
    chapterNumber: 10,
    title: "Build a mini deep learning framework from scratch",
    blurb: "Write Tensor abstractions, layers, loss functions, and AdamW optimizer.",
    capstone: true,
  },

  // ---------- Part IX — Deep Learning Regularization, Normalization & Training Dynamics ----------
  {
    slug: "weight-initialization",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 1,
    title: "Weight initialization (Xavier & He/Kaiming)",
    blurb: "Preserve activation and gradient variance across deep layers.",
  },
  {
    slug: "vanishing-and-exploding-gradients",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 2,
    title: "Vanishing & exploding gradients",
    blurb: "Analyze spectral norms, gradient explosion, and gradient clipping.",
  },
  {
    slug: "batch-normalization",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 3,
    title: "Batch normalization",
    blurb: "Normalize activations across mini-batches to accelerate convergence.",
  },
  {
    slug: "layer-and-group-normalization",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 4,
    title: "Layer normalization & Group normalization",
    blurb: "Normalize across feature channels for small batches and sequences.",
  },
  {
    slug: "rmsnorm",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 5,
    title: "RMSNorm",
    blurb: "Streamline normalization by scaling by root-mean-square without mean subtraction.",
  },
  {
    slug: "dropout",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 6,
    title: "Dropout & stochastic depth",
    blurb: "Stochastically deactivate neurons during training to prevent co-adaptation.",
  },
  {
    slug: "weight-decay-vs-l2",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 7,
    title: "Weight decay vs. L2 regularization",
    blurb: "Understand why decoupled weight decay is essential when using Adam.",
  },
  {
    slug: "learning-rate-schedules",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 8,
    title: "Learning rate schedules: Warmup & Cosine decay",
    blurb: "Warm up learning rates and decay smoothly with cosine annealing.",
  },
  {
    slug: "mixed-precision-training",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 9,
    title: "Mixed precision training (FP16 & BF16)",
    blurb: "Accelerate training and conserve memory with dynamic loss scaling.",
  },
  {
    slug: "capstone-stabilize-deep-network",
    part: "Part IX — Deep Learning Regularization, Normalization & Training Dynamics",
    chapterNumber: 10,
    title: "Train and stabilize a 20-layer neural network",
    blurb: "Overcome vanishing gradients using modern initialization, RMSNorm, and AdamW.",
    capstone: true,
  },

  // ---------- Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation ----------
  {
    slug: "convolution",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 1,
    title: "Convolution & 2D spatial filtering",
    blurb: "Slide 2D kernels across images with stride, dilation, and padding.",
  },
  {
    slug: "pooling",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 2,
    title: "Pooling & spatial downsampling",
    blurb: "Downsample feature maps with max and average pooling operations.",
  },
  {
    slug: "a-minimal-cnn",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 3,
    title: "A minimal CNN architecture",
    blurb: "Assemble convolutions, activations, and pooling into a working classifier.",
  },
  {
    slug: "resnet-and-residual-connections",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 4,
    title: "ResNet & residual skip connections",
    blurb: "Allow gradient signals to pass unimpeded through 100+ layer networks.",
  },
  {
    slug: "inverted-residuals-and-mobilenets",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 5,
    title: "Inverted residuals & MobileNets",
    blurb: "Depthwise separable convolutions for efficient edge computing.",
  },
  {
    slug: "transfer-learning-and-fine-tuning",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 6,
    title: "Transfer learning & feature extraction",
    blurb: "Repurpose pretrained vision representations for downstream tasks.",
  },
  {
    slug: "object-detection-and-segmentation",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 7,
    title: "Object detection fundamentals (Bounding Boxes & IoU)",
    blurb: "Predict bounding box coordinates and filter overlaps using NMS.",
  },
  {
    slug: "one-stage-vs-two-stage-detectors",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 8,
    title: "One-stage vs. two-stage detectors (YOLO vs. Faster R-CNN)",
    blurb: "Compare single-pass grid predictions with region proposal networks.",
  },
  {
    slug: "semantic-segmentation-and-unet",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 9,
    title: "Semantic segmentation & the U-Net",
    blurb: "Encoder-decoder architecture with contracting and expansive skip paths.",
  },
  {
    slug: "capstone-classify-digits",
    part: "Part X — Computer Vision: CNNs, ResNets, Object Detection & Segmentation",
    chapterNumber: 10,
    title: "Train a CNN and inspect its learned feature filters",
    blurb: "Train a CNN live in the browser and visualize convolutional kernel activations.",
    capstone: true,
  },

  // ---------- Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block ----------
  {
    slug: "why-sequences-break-feedforward-nets",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 1,
    title: "Why sequences break feedforward networks",
    blurb: "Variable context length, token order, and temporal dependencies.",
  },
  {
    slug: "recurrent-neural-networks",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 2,
    title: "Recurrent Neural Networks (RNN)",
    blurb: "Propagate hidden states step-by-step through recurrent loops.",
  },
  {
    slug: "vanishing-gradients-and-lstms",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 3,
    title: "Vanishing gradients in RNNs & LSTMs",
    blurb: "Protect long-term sequence memories with forget, input, and output gates.",
  },
  {
    slug: "gru",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 4,
    title: "The Gated Recurrent Unit (GRU)",
    blurb: "Streamline recurrence by merging cell states and hidden states.",
  },
  {
    slug: "sequence-to-sequence",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 5,
    title: "Sequence-to-Sequence models & encoder-decoders",
    blurb: "Compress source sequences into fixed vectors and decode target sequences.",
  },
  {
    slug: "word-embeddings",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 6,
    title: "Word embeddings (Word2Vec & GloVe)",
    blurb: "Map discrete vocabulary tokens into dense continuous semantic vector spaces.",
  },
  {
    slug: "tokenization",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 7,
    title: "Tokenization & Byte-Pair Encoding (BPE)",
    blurb: "Segment raw text into subword token vocabularies.",
  },
  {
    slug: "attention",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 8,
    title: "The attention mechanism",
    blurb: "Dynamic alignment allowing every token to query the entire sequence.",
  },
  {
    slug: "self-attention-and-multi-head-attention",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 9,
    title: "Self-attention & multi-head attention",
    blurb: "Compute Query-Key-Value dot products across parallel projection subspaces.",
  },
  {
    slug: "capstone-transformer-block",
    part: "Part XI — Sequence Models: RNNs, LSTMs, Attention & The Transformer Block",
    chapterNumber: 10,
    title: "Build a complete Transformer block from scratch",
    blurb: "Assemble Multi-Head Attention, LayerNorm, Residual connections, and MLPs.",
    capstone: true,
  },

  // ---------- Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models ----------
  {
    slug: "positional-encodings-sinusoidal-and-relative",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 1,
    title: "Positional encodings: Sinusoidal vs. Relative",
    blurb: "Inject token order into permutation-invariant attention matrices.",
  },
  {
    slug: "rotary-position-embedding-rope",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 2,
    title: "Rotary Position Embedding (RoPE)",
    blurb: "Rotate query and key vectors in 2D coordinate pairs to preserve relative distances.",
  },
  {
    slug: "context-window-scaling-yarn",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 3,
    title: "Context window scaling (YaRN & LongRoPE)",
    blurb: "Interpolate RoPE frequencies to extend context length from 8k to 128k+ tokens.",
  },
  {
    slug: "the-quadratic-bottleneck",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 4,
    title: "The quadratic attention bottleneck",
    blurb: "Quantify the O(N^2) memory and compute cost of full self-attention.",
  },
  {
    slug: "flash-attention-algorithms",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 5,
    title: "FlashAttention (1, 2, 3) & GPU memory hierarchies",
    blurb: "Tiling attention computations between SRAM and HBM using online softmax.",
  },
  {
    slug: "linear-attention",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 6,
    title: "Linear attention & kernelized approximations",
    blurb: "Swap softmax for kernel feature maps to achieve O(N) linear time attention.",
  },
  {
    slug: "state-space-models",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 7,
    title: "State-space models (SSM & S4)",
    blurb: "Discretize continuous linear dynamical systems into efficient sequence models.",
  },
  {
    slug: "selective-state-spaces",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 8,
    title: "Selective state spaces (Mamba / Mamba-2)",
    blurb: "Input-dependent time-varying parameters and hardware-accelerated associative scans.",
  },
  {
    slug: "hybrid-transformer-ssm-architectures",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 9,
    title: "Hybrid architectures (Jamba & recurrent attention)",
    blurb: "Combine Transformer attention layers with Mamba SSM blocks.",
  },
  {
    slug: "capstone-transformer-vs-mamba",
    part: "Part XII — Modern Sequence Architectures: RoPE, FlashAttention & State-Space Models",
    chapterNumber: 10,
    title: "Transformer vs. Mamba on a 128k sequence benchmark",
    blurb: "Profile speed, memory consumption, and needle-in-a-haystack retrieval accuracy.",
    capstone: true,
  },

  // =========================================================================
  // PHASE 4: GENERATIVE AI & MULTIMODAL SYSTEMS
  // =========================================================================

  // ---------- Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers ----------
  {
    slug: "autoencoders",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 1,
    title: "Autoencoders & latent space representations",
    blurb: "Compress images through a latent bottleneck and reconstruct them.",
  },
  {
    slug: "variational-autoencoders",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 2,
    title: "Variational Autoencoders (VAE)",
    blurb: "Sample continuous latents using the reparameterization trick and ELBO loss.",
  },
  {
    slug: "vq-vae-discrete-latents",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 3,
    title: "VQ-VAE & discrete latent codebooks",
    blurb: "Quantize continuous vectors to discrete codebook entries for generative modeling.",
  },
  {
    slug: "normalizing-flows",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 4,
    title: "Normalizing flows & invertible transformations",
    blurb: "Track exact probability densities through invertible neural network layers.",
  },
  {
    slug: "score-based-generative-models",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 5,
    title: "Score-based generative models",
    blurb: "Follow gradients of log-density via Langevin dynamics to denoise samples.",
  },
  {
    slug: "diffusion-models",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 6,
    title: "Denoising Diffusion Probabilistic Models (DDPM)",
    blurb: "Step-by-step Gaussian forward corruption and learned reverse denoising.",
  },
  {
    slug: "deterministic-sampling-ddim",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 7,
    title: "Deterministic sampling with DDIM",
    blurb: "Accelerate reverse diffusion using non-Markovian deterministic ODE trajectories.",
  },
  {
    slug: "flow-matching",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 8,
    title: "Continuous-time flow matching",
    blurb: "Learn straight optimal transport velocity fields between noise and data distributions.",
  },
  {
    slug: "diffusion-transformers-dit",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 9,
    title: "Diffusion Transformers (DiT / Flux / SD3)",
    blurb: "Replace convolutional U-Net denoisers with scalable Transformer backbones.",
  },
  {
    slug: "capstone-build-a-flow-matching-sampler",
    part: "Part XIII — Generative Models: VAEs, Flow Matching, Score Models & Diffusion Transformers",
    chapterNumber: 10,
    title: "Build a flow-matching & DiT image synthesizer",
    blurb: "Train a velocity vector field and sample generated images with ODE solvers.",
    capstone: true,
  },

  // ---------- Part XIV — 3D Vision, Neural Fields & Gaussian Splatting ----------
  {
    slug: "representing-3d-data",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 1,
    title: "Representing 3D data: Point clouds, meshes & SDFs",
    blurb: "Represent geometry through discrete point sets, polygon meshes, and signed distance fields.",
  },
  {
    slug: "camera-projections-and-coordinate-systems",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 2,
    title: "Camera projections & ray casting",
    blurb: "Pinhole cameras, intrinsic/extrinsic matrices, and casting rays into 3D space.",
  },
  {
    slug: "neural-radiance-fields-nerf",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 3,
    title: "Neural Radiance Fields (NeRF)",
    blurb: "Synthesize novel views via continuous volumetric rendering functions.",
  },
  {
    slug: "instant-ngp-and-hash-encoding",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 4,
    title: "Instant-NGP & spatial multiresolution hash grids",
    blurb: "Accelerate neural field training from hours to seconds with hash encodings.",
  },
  {
    slug: "3d-gaussian-splatting-fundamentals",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 5,
    title: "3D Gaussian Splatting (3DGS) fundamentals",
    blurb: "Represent 3D scenes as millions of anisotropic 3D ellipsoidal Gaussians.",
  },
  {
    slug: "rasterization-and-optimization-in-3dgs",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 6,
    title: "Tile-based differentiable rasterization in 3DGS",
    blurb: "Sort Gaussians and project them in real time with adaptive densification.",
  },
  {
    slug: "generative-3d-ai-and-mesh-synthesis",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 7,
    title: "Generative 3D AI & single-image reconstruction",
    blurb: "Generate full 3D meshes from single 2D images with feedforward triplane networks.",
  },
  {
    slug: "capstone-3d-gaussian-splatting-renderer",
    part: "Part XIV — 3D Vision, Neural Fields & Gaussian Splatting",
    chapterNumber: 8,
    title: "Train and render a 3D Gaussian Splatting scene",
    blurb: "Optimize 3D Gaussians from multi-view photographs and render in real time.",
    capstone: true,
  },

  // ---------- Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs ----------
  {
    slug: "joint-embedding-spaces",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 1,
    title: "Joint multimodal embedding spaces",
    blurb: "Project images, text, and audio into a unified semantic metric space.",
  },
  {
    slug: "contrastive-learning",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 2,
    title: "Contrastive learning & CLIP",
    blurb: "InfoNCE loss, symmetric cross-entropy, and zero-shot image classification.",
  },
  {
    slug: "cross-attention",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 3,
    title: "Cross-attention mechanisms",
    blurb: "Condition generation by querying visual features with text tokens.",
  },
  {
    slug: "vision-language-models-assembled",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 4,
    title: "Vision-Language Models (VLM) assembled",
    blurb: "Connect vision encoders with autoregressive language models.",
  },
  {
    slug: "patch-projectors-and-image-tokenization",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 5,
    title: "Patch projectors & image tokenization",
    blurb: "Convert 2D image patches into embedding tokens with linear and Perceiver projectors.",
  },
  {
    slug: "interleaved-multimodal-generation",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 6,
    title: "Interleaved multimodal generation",
    blurb: "Generate mixed sequences of text and image tokens in a single stream.",
  },
  {
    slug: "audio-and-speech-embeddings",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 7,
    title: "Audio & speech embeddings (Whisper)",
    blurb: "Extract mel-spectrograms and align acoustic representations with language.",
  },
  {
    slug: "video-understanding",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 8,
    title: "Video understanding & spatiotemporal attention",
    blurb: "Process multi-frame video sequences across spatial and temporal dimensions.",
  },
  {
    slug: "retrieval-augmented-generation",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 9,
    title: "Retrieval-Augmented Generation (RAG)",
    blurb: "Ground multimodal responses with dense vector search and reranking.",
  },
  {
    slug: "capstone-image-text-search-engine",
    part: "Part XV — Multimodal Foundation Models: CLIP, Cross-Attention & VLMs",
    chapterNumber: 10,
    title: "Build a multimodal visual question answering assistant",
    blurb: "Combine visual embeddings, dense retrieval, and a VLM into a working assistant.",
    capstone: true,
  },

  // =========================================================================
  // PHASE 5: REINFORCEMENT LEARNING, POST-TRAINING & REASONING
  // =========================================================================

  // ---------- Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO ----------
  {
    slug: "multi-armed-bandits",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 1,
    title: "Multi-armed bandits (Epsilon-greedy & UCB)",
    blurb: "Balance exploration vs. exploitation across uncertain payoff distributions.",
  },
  {
    slug: "markov-decision-processes",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 2,
    title: "Markov Decision Processes (MDP)",
    blurb: "States, actions, state transitions, rewards, and discount factors.",
  },
  {
    slug: "value-functions-and-bellman-equations",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 3,
    title: "Value functions & Bellman equations",
    blurb: "Recursive decomposition of expected cumulative future rewards.",
  },
  {
    slug: "dynamic-programming-policy-value-iteration",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 4,
    title: "Policy iteration & value iteration",
    blurb: "Solve exact optimal policies when transition dynamics are fully known.",
  },
  {
    slug: "q-learning",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 5,
    title: "Q-learning & temporal-difference updates",
    blurb: "Learn optimal action-value tables through off-policy bootstrapping.",
  },
  {
    slug: "deep-q-networks",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 6,
    title: "Deep Q-Networks (DQN)",
    blurb: "Stabilize neural Q-function estimation with experience replay and target networks.",
  },
  {
    slug: "policy-gradient-methods",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 7,
    title: "Policy gradient methods (REINFORCE)",
    blurb: "Directly ascend expected reward gradients using the log-derivative trick.",
  },
  {
    slug: "actor-critic-architectures",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 8,
    title: "Actor-Critic architectures (A2C/A3C)",
    blurb: "Reduce policy gradient variance by subtracting value function baselines.",
  },
  {
    slug: "proximal-policy-optimization-ppo",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 9,
    title: "Proximal Policy Optimization (PPO)",
    blurb: "Clip probability ratio updates to prevent destructive policy collapse.",
  },
  {
    slug: "capstone-train-an-agent-in-a-gridworld",
    part: "Part XVI — Reinforcement Learning: Bandits, MDPs, Policy Gradients & PPO",
    chapterNumber: 10,
    title: "Solve a complex gridworld environment with PPO",
    blurb: "Train an autonomous agent live from scratch using Proximal Policy Optimization.",
    capstone: true,
  },

  // ---------- Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute ----------
  {
    slug: "the-modern-llm-post-training-pipeline",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 1,
    title: "The modern LLM post-training pipeline",
    blurb: "Deconstruct the journey from pretraining to SFT, preference alignment, and reasoning RL.",
  },
  {
    slug: "instruction-tuning-and-sft",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 2,
    title: "Instruction tuning & Supervised Fine-Tuning (SFT)",
    blurb: "Curate high-quality conversational datasets and apply loss masking.",
  },
  {
    slug: "reinforcement-learning-from-human-feedback",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 3,
    title: "RLHF: Bradley-Terry reward modeling",
    blurb: "Fit reward models to human pairwise preference data and align policies via PPO.",
  },
  {
    slug: "direct-preference-optimization",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 4,
    title: "Direct Preference Optimization (DPO)",
    blurb: "Derive closed-form preference optimization without training an explicit reward model.",
  },
  {
    slug: "advanced-preference-kto-simpo",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 5,
    title: "Advanced preference alignment (KTO & SimPO)",
    blurb: "Align on unpaired feedback and reference-free target margins.",
  },
  {
    slug: "group-relative-policy-optimization-grpo",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 6,
    title: "Group Relative Policy Optimization (GRPO / DeepSeek-R1)",
    blurb: "Eliminate critic networks by normalizing advantages across sampled groups.",
  },
  {
    slug: "reinforcement-learning-with-verifiable-rewards-rlvr",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 7,
    title: "RL with Verifiable Rewards (RLVR)",
    blurb: "Deterministic programmatic reward verification for math and competitive coding.",
  },
  {
    slug: "reasoning-models-and-test-time-compute",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 8,
    title: "Reasoning models & test-time compute scaling",
    blurb: "Trade inference latency for accuracy via long Chain-of-Thought (CoT) and self-reflection.",
  },
  {
    slug: "process-reward-models-and-tree-search",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 9,
    title: "Process Reward Models (PRM) & Monte Carlo Tree Search",
    blurb: "Score reasoning step-by-step and search token trajectories with MCTS.",
  },
  {
    slug: "capstone-train-a-reasoning-model-grpo",
    part: "Part XVII — LLM Post-Training: SFT, DPO, GRPO & Reasoning / Test-Time Compute",
    chapterNumber: 10,
    title: "Train a reasoning model using GRPO & verifiable rewards",
    blurb: "Train a compact model to produce verifiable step-by-step mathematical reasoning.",
    capstone: true,
  },

  // =========================================================================
  // PHASE 6: AGENTS, SAFETY, SYSTEMS & EMBODIED AI
  // =========================================================================

  // ---------- Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms ----------
  {
    slug: "function-calling-and-tool-use",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 1,
    title: "Function calling & tool use",
    blurb: "Emit structured JSON tool arguments and parse external environment outputs.",
  },
  {
    slug: "react-reasoning-and-acting",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 2,
    title: "The ReAct paradigm: Reasoning & Acting",
    blurb: "Interleave Thought, Action, and Observation loops to solve multi-step problems.",
  },
  {
    slug: "planning-and-task-decomposition",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 3,
    title: "Planning & hierarchical task decomposition",
    blurb: "Decompose ambiguous goals into ordered subtasks with dynamic replanning.",
  },
  {
    slug: "agent-memory",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 4,
    title: "Agent memory: Short-term scratchpad vs. Long-term vector store",
    blurb: "Manage context windows and retrieve episodic memories dynamically.",
  },
  {
    slug: "environment-feedback-and-reflexion",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 5,
    title: "Environment feedback & self-reflection (Reflexion)",
    blurb: "Analyze compiler errors and terminal logs to self-correct execution mistakes.",
  },
  {
    slug: "multi-agent-orchestration",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 6,
    title: "Multi-agent orchestration & swarms",
    blurb: "Coordinator-worker architectures, agent role specialization, and debate protocols.",
  },
  {
    slug: "agent-benchmarking-and-swe-bench",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 7,
    title: "Agent benchmarking & SWE-bench evaluation",
    blurb: "Evaluate software engineering agents on real-world GitHub issues.",
  },
  {
    slug: "agent-sandboxing-and-security",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 8,
    title: "Agent sandboxing & execution security",
    blurb: "Isolate agent code execution within secure Docker/WASM sandboxes.",
  },
  {
    slug: "human-in-the-loop-agent-systems",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 9,
    title: "Human-in-the-loop approval workflows",
    blurb: "Design approval checkpoints, budget thresholds, and user interventions.",
  },
  {
    slug: "capstone-build-a-tool-using-agent",
    part: "Part XVIII — LLM Agents, Tool Use, Planning & Multi-Agent Swarms",
    chapterNumber: 10,
    title: "Build an autonomous software engineering agent",
    blurb: "Construct an agent that reads files, modifies code, runs tests, and fixes bugs.",
    capstone: true,
  },

  // ---------- Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming ----------
  {
    slug: "constitutional-ai-and-rlaif",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 1,
    title: "Constitutional AI & RLAIF",
    blurb: "Automated principle-based self-critique and revision without human annotations.",
  },
  {
    slug: "adversarial-examples-and-robustness",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 2,
    title: "Adversarial attacks & robustness (FGSM & PGD)",
    blurb: "Generate input perturbations that fool classifiers while remaining imperceptible.",
  },
  {
    slug: "jailbreaks-and-red-teaming",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 3,
    title: "LLM jailbreaks, prompt injections & red-teaming",
    blurb: "Audit safety filters against indirect injections, base64 obfuscation, and persona hijacks.",
  },
  {
    slug: "fairness-metrics-and-bias-auditing",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 4,
    title: "Fairness metrics & bias auditing",
    blurb: "Compute demographic parity, equalized odds, and calibration disparity.",
  },
  {
    slug: "mechanistic-interpretability-fundamentals",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 5,
    title: "Mechanistic interpretability fundamentals",
    blurb: "Probe internal representations using linear probing and activation patching.",
  },
  {
    slug: "mechanistic-interpretability-and-saes",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 6,
    title: "Sparse Autoencoders (SAE) & monosemanticity",
    blurb: "Decompose polysemantic hidden activations into clean monosemantic feature dictionaries.",
  },
  {
    slug: "circuit-tracing-and-induction-heads",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 7,
    title: "Circuit tracing & induction heads",
    blurb: "Trace specific attention head circuits responsible for in-context pattern replication.",
  },
  {
    slug: "model-editing-rome-memit",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 8,
    title: "Model editing (ROME & MEMIT)",
    blurb: "Locate and update specific factual associations directly in MLP weights.",
  },
  {
    slug: "hallucination-detection-and-calibration",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 9,
    title: "Hallucination detection & semantic entropy",
    blurb: "Measure internal model uncertainty to flag hallucinations before output generation.",
  },
  {
    slug: "capstone-red-team-and-patch-a-model",
    part: "Part XIX — Alignment, Mechanistic Interpretability, Safety & Red-Teaming",
    chapterNumber: 10,
    title: "Red-team, interpret, and safety-patch a model",
    blurb: "Extract features with an SAE, discover a vulnerability, and patch it in place.",
    capstone: true,
  },

  // ---------- Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps ----------
  {
    slug: "embodied-ai-and-vla-robotics",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 1,
    title: "Embodied AI & Vision-Language-Action (VLA) models",
    blurb: "Map visual camera observations directly to low-level robotic motor torques (RT-2/OpenVLA/pi0).",
  },
  {
    slug: "diffusion-policies-for-manipulation",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 2,
    title: "Diffusion policies for robotic manipulation",
    blurb: "Predict smooth, multi-modal continuous physical action trajectories using flow matching.",
  },
  {
    slug: "sim-to-real-transfer-and-physics-engines",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 3,
    title: "Sim-to-real transfer & physics engines (MuJoCo / Isaac)",
    blurb: "Bridge the reality gap with domain randomization and high-throughput GPU physics.",
  },
  {
    slug: "gpu-memory-hierarchies-and-profiling",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 4,
    title: "GPU memory hierarchies & kernel profiling",
    blurb: "Understand SRAM vs. HBM bandwidth, Tensor Core utilization, and arithmetic intensity.",
  },
  {
    slug: "model-quantization-awq-gptq-gguf",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 5,
    title: "Quantization (AWQ, GPTQ, GGUF & BitNet 1.58-bit)",
    blurb: "Compress model weights into FP8, INT4, and ternary 1.58-bit representations.",
  },
  {
    slug: "inference-acceleration-pagedattention-vllm",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 6,
    title: "High-throughput serving: PagedAttention & vLLM",
    blurb: "Manage dynamic KV-cache memory blocks without fragmentation to achieve 10x throughput.",
  },
  {
    slug: "speculative-decoding-and-medusa",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 7,
    title: "Speculative decoding & Medusa heads",
    blurb: "Draft multiple future tokens concurrently and verify in parallel to reduce latency.",
  },
  {
    slug: "distributed-training-parallelism",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 8,
    title: "Large-scale distributed training (DDP, FSDP, ZeRO & Megatron-LM)",
    blurb: "Distribute massive models across clusters using Tensor, Pipeline, and Sequence Parallelism.",
  },
  {
    slug: "vector-databases-and-ann-search",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 9,
    title: "Vector databases & ANN search (HNSW & IVF-PQ)",
    blurb: "Index millions of embeddings and query nearest neighbors in sub-millisecond time.",
  },
  {
    slug: "data-pipelines-and-feature-stores",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 10,
    title: "Data pipelines & feature stores (Feast)",
    blurb: "Ensure point-in-time correctness and synchronize offline training with online serving.",
  },
  {
    slug: "model-monitoring-and-drift",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 11,
    title: "Model monitoring, drift detection & canary rollouts",
    blurb: "Detect covariate and concept drift with Kolmogorov-Smirnov and PSI statistics.",
  },
  {
    slug: "capstone-design-a-monitored-serving-pipeline",
    part: "Part XX — Embodied AI & Production Systems: VLA Robotics, High-Throughput Serving & MLOps",
    chapterNumber: 12,
    title: "Build and deploy a monitored, high-throughput AI serving cluster",
    blurb: "Deploy a vLLM serving pipeline with INT4 AWQ quantization, Prometheus metrics, and drift alarms.",
    capstone: true,
  },

  // =========================================================================
  // PHASE 7: SPECIALIZED & CLASSICAL TOPICS
  // =========================================================================

  // ---------- Part XXI — Explainable AI & Model Interpretability ----------
  {
    slug: "interpretability-accuracy-tradeoff",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 1,
    title: "The interpretability–accuracy tradeoff",
    blurb: "Why the most accurate model on the leaderboard is often the least explainable.",
  },
  {
    slug: "saliency-maps",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 2,
    title: "Saliency maps",
    blurb: "Highlight exactly which pixels actually moved a prediction.",
  },
  {
    slug: "grad-cam",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 3,
    title: "Grad-CAM",
    blurb: "See what a CNN was visually \"looking at\" the moment it decided.",
  },
  {
    slug: "integrated-gradients",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 4,
    title: "Integrated gradients",
    blurb: "Walk a straight line from a blank baseline to the real input, and integrate the gradient the whole way there.",
  },
  {
    slug: "lime",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 5,
    title: "LIME",
    blurb: "Explain any black-box model by locally approximating it with something simple.",
  },
  {
    slug: "shapley-values",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 6,
    title: "Shapley values",
    blurb: "A game-theoretic, provably fair way to split credit among features.",
  },
  {
    slug: "shap-for-real-models",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 7,
    title: "SHAP for real models",
    blurb: "Shapley values made practical and applied to an actual trained classifier.",
  },
  {
    slug: "counterfactual-explanations",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 8,
    title: "Counterfactual explanations",
    blurb: "\"What's the smallest change that would have flipped this decision?\"",
  },
  {
    slug: "capstone-explain-one-prediction-three-ways",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 9,
    title: "Explain one prediction three ways",
    blurb: "Saliency, SHAP, and a counterfactual on the same case, compared side by side.",
    capstone: true,
  },
  {
    slug: "partial-dependence-plots",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 10,
    title: "Partial dependence & ICE plots",
    blurb: "Sweep one feature across its whole range and watch the model's average answer trace a curve.",
  },
  {
    slug: "tree-feature-importance",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 11,
    title: "Tree-based feature importance",
    blurb: "Read off which feature did the most work — for free, from a forest you already trained.",
  },
  {
    slug: "anchors-rule-based-explanations",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 12,
    title: "Anchors: rule-based explanations",
    blurb: "Replace a linear local approximation with a simple if-then rule that's true almost everywhere nearby.",
  },
  {
    slug: "capstone-audit-a-model-five-ways",
    part: "Part XXI — Explainable AI & Model Interpretability",
    chapterNumber: 13,
    title: "Audit one model, five different ways",
    blurb: "Saliency, SHAP, PDP, tree importance, and an Anchor rule, on the exact same prediction.",
    capstone: true,
  },

  // ---------- Part XXII — Graph Neural Networks & Structured Data ----------
  {
    slug: "graphs-as-data",
    part: "Part XXII — Graph Neural Networks & Structured Data",
    chapterNumber: 1,
    title: "Graphs as data",
    blurb: "Turn a handful of dots and lines into an adjacency matrix, and see why a grid convolution has nowhere to slide.",
  },
  {
    slug: "message-passing-and-gcn",
    part: "Part XXII — Graph Neural Networks & Structured Data",
    chapterNumber: 2,
    title: "Message passing & the GCN",
    blurb: "Watch a node's feature update by averaging its neighbors', layer after layer, until far-apart nodes start to look alike.",
  },
  {
    slug: "graphsage-inductive-learning",
    part: "Part XXII — Graph Neural Networks & Structured Data",
    chapterNumber: 3,
    title: "GraphSAGE: inductive learning on graphs",
    blurb: "Sample a handful of neighbors instead of all of them, then apply the same rule to a node the network has never seen.",
  },
  {
    slug: "graph-attention-networks",
    part: "Part XXII — Graph Neural Networks & Structured Data",
    chapterNumber: 4,
    title: "Graph attention networks",
    blurb: "Give every neighbor its own attention weight instead of a flat average, and watch the important ones dominate.",
  },
  {
    slug: "capstone-predict-a-molecules-property",
    part: "Part XXII — Graph Neural Networks & Structured Data",
    chapterNumber: 5,
    title: "Predict a molecule's property from its bonds",
    blurb: "Wire message passing and attention together to guess a tiny molecule's property from its atoms and bonds alone.",
    capstone: true,
  },

  // ---------- Part XXIII — Modern Architectures, Generative Models & LLM Engineering ----------
  {
    slug: "vision-transformers",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 1,
    title: "Vision Transformers",
    blurb: "Cut an image into patches, and feed them to the exact same block that already reads sentences.",
  },
  {
    slug: "bert-and-masked-language-modeling",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 2,
    title: "BERT & masked language modeling",
    blurb: "Hide a word in the middle of a sentence and watch a model reconstruct it from both directions at once.",
  },
  {
    slug: "generative-adversarial-networks",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 3,
    title: "Generative adversarial networks",
    blurb: "Two networks compete — one forges, one detects — and both get better together.",
  },
  {
    slug: "consistency-models",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 4,
    title: "Consistency models",
    blurb: "Collapse an entire denoising trajectory onto one endpoint, and generate a sample in a single jump.",
  },
  {
    slug: "text-conditioned-diffusion",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 5,
    title: "Text-conditioned diffusion",
    blurb: "Steer the reverse-noise process with a caption, and watch the same denoiser draw a different picture.",
  },
  {
    slug: "mixture-of-experts",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 6,
    title: "Mixture-of-experts",
    blurb: "Add a router that sends each token to only two of dozens of feedforward blocks.",
  },
  {
    slug: "lora-and-parameter-efficient-fine-tuning",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 7,
    title: "LoRA & parameter-efficient fine-tuning",
    blurb: "Freeze a huge weight matrix, and learn only a tiny low-rank update instead.",
  },
  {
    slug: "prompting-and-in-context-learning",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 8,
    title: "Prompting & in-context learning",
    blurb: "Change nothing but the input, and watch a frozen model's answer change anyway.",
  },
  {
    slug: "scaling-laws",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 9,
    title: "Scaling laws",
    blurb: "Fit a straight line through a log-log plot, and predict a loss you haven't trained for yet.",
  },
  {
    slug: "experiment-tracking-and-reproducibility",
    part: "Part XXIII — Modern Architectures, Generative Models & LLM Engineering",
    chapterNumber: 10,
    title: "Experiment tracking & reproducibility",
    blurb: "Change one hyperparameter, keep everything else fixed, and see why \"everything else\" is the hard part to guarantee.",
  },
];

export function getChapterMeta(slug: string): ChapterMeta {
  const meta = CURRICULUM.find((c) => c.slug === slug);
  if (!meta) throw new Error(`Unknown chapter slug: ${slug}`);
  return meta;
}

export interface ChapterNeighbors {
  index: number;
  prev: ChapterMeta | null;
  next: ChapterMeta | null;
}

export function getChapterNeighbors(slug: string): ChapterNeighbors {
  const index = CURRICULUM.findIndex((c) => c.slug === slug);
  return {
    index,
    prev: index > 0 ? CURRICULUM[index - 1] : null,
    next: index >= 0 && index < CURRICULUM.length - 1 ? CURRICULUM[index + 1] : null,
  };
}
